### ISSUE TITLE
Batch IDs & sample-level QC measures

### ISSUE THREAD

**Issue by AswinSSoman** [markrobinsonuzh/conquer#5]
Where can I find 'batch IDs' & sample-level QC measures like 'run IDs' other than the 'num_processed', 'num_mapped', & 'percent_mapped' in metadata$salmon_summary?

**Comment by csoneson** [comment]
The sample annotations that we downloaded or generated are provided either in the `colData` of the `MultiAssayExperiment` object, or in the Salmon metadata. I'm not sure exactly which 'batch IDs' you are looking for (and for which data set), but if they were not provided in the GEO record, they will not be in the provided objects.

**Comment by AswinSSoman** [comment]
I was interested in removing batch effects for which I need to know the experimental batches used. 

If I'm using smaller dataset like GSE66507(30 human pre-implantation embryos); I'm not sure which slot corresponds to experimental batch. Is it the characteristics_ch1.2 (embryo number) the 'batch IDs' in this case?  

Best regards, 
Aswin

**Comment by csoneson** [comment]
You would have to infer which (if any) annotation column corresponds to the 'experimental batch' variable from the information provided in the publication or the original data repository record - it is unlikely to always be represented in the same column. Note that, as I mentioned previously, we did not curate the metadata manually, and the information included in the data objects in conquer is all obtained from the GEO metadata. Also note that in general, 'experimental batch' can mean many things - the samples can be processed in batches at the stages of library preparation, sequencing, etc, each of which can introduce batch effects.
